### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by billiemead** [baoboine/botble-comment#2]
Hello, I am trying to run php artisan passport:install but am getting an error. 

I first ran php artisan migrate --path=/platform/plugins/comment/database/migrations/2021_07_08_140130_comment_create_comment_table.php

Then in the folder /platform/plugins/comment/ I ran composer update 

But what about php artisan passport:install ? Do I run this in the /platform/plugins/comment folder? 

Thx

**Comment by baoboine** [comment]
@billiemead No... You don't need to go to /platform/plugins/comment
Just run commands at root of your source.

First, please active Comment plugin. It can works without passport from version 3.0 ^^

**Comment by billiemead** [comment]
@baoboine Thank you for taking the time to reply!

Also, can I reach you on a private channel (email)? I'd like to develop a few plugins to sell on Codecanyon but only want to do it in line with your planned features.

Cheers, Billie

**Comment by baoboine** [comment]
@billiemead Yes. My email: suysiutnhan@gmail.com
